/// Flutter icons CineApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CineApp
///      fonts:
///       - asset: fonts/CineApp.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class CineApp {
  CineApp._();

  static const _kFontFam = 'CineApp';
  static const String? _kFontPkg = null;

  static const IconData cinema_ticket_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popcorn = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData film_reel = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cinema_screen = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cinema_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armchair_2_1ju = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armchair_1id = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData film_play = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
