// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfpAEGXg6U-9HDEqAhnBH54vdHjzR-ZAs',
    appId: '1:426947305947:web:92f0db9be941ce1ed307fe',
    messagingSenderId: '426947305947',
    projectId: 'cineapp-a86ac',
    authDomain: 'cineapp-a86ac.firebaseapp.com',
    storageBucket: 'cineapp-a86ac.appspot.com',
    measurementId: 'G-2E2NWBHP5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKyPza5aOFvwdF_R-p26yJn825ydW-UoA',
    appId: '1:426947305947:android:c7a476f232dd2764d307fe',
    messagingSenderId: '426947305947',
    projectId: 'cineapp-a86ac',
    storageBucket: 'cineapp-a86ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0B_a9nc8R7efCdFrkRUuIvpE8fJRvmv8',
    appId: '1:426947305947:ios:04e6aeb78790e622d307fe',
    messagingSenderId: '426947305947',
    projectId: 'cineapp-a86ac',
    storageBucket: 'cineapp-a86ac.appspot.com',
    iosClientId: '426947305947-stvb3g5pa4hnufaetnhomer2mcaiq4jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0B_a9nc8R7efCdFrkRUuIvpE8fJRvmv8',
    appId: '1:426947305947:ios:04e6aeb78790e622d307fe',
    messagingSenderId: '426947305947',
    projectId: 'cineapp-a86ac',
    storageBucket: 'cineapp-a86ac.appspot.com',
    iosClientId: '426947305947-stvb3g5pa4hnufaetnhomer2mcaiq4jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
